"""Pilot experiment, step 3: held-out evaluation of the CMA-ES result against v3_2.

  export   rl/out/<run>/mean_z.npy -> minifly/v3_2_es.yaml (v3_2 YAML + optimised decoder values)
  twin     cage20 (never trained on) in the fast twin, both variants, N seeds
  gazebo   gz_g4_rl.sh (waits for an idle Gazebo, never kills another session), GPS patrol 120 s as matrix_v32,
           seeds interleaved v3_2 / es so drift in the machine load hits both arms; RTF < 0.95 -> rerun once
  report   both arms side by side + Fisher exact test on contact runs, Mann-Whitney on near misses / coverage

python -m rl.validate export --run es1
python -m rl.validate gazebo --seeds 0-31
python -m rl.validate report --seeds 0-31
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import numpy as np
import yaml

from rl import params
from rl.episode import deep_merge

E = Path(__file__).resolve().parent.parent
RUNS = Path.home() / "sim" / "rl_exp" / "runs"
ES_YAML = E / "minifly" / "v3_2_es.yaml"
ARGS = "--mode patrol --seconds 120 --cruise 0.5 --max-forward 0.5 --fence-turn --decoder ecps --pilot ecps --retina ecps --port 0 --out run"


def export(run: str, which: str = "mean") -> None:
    z = np.load(E / "rl" / "out" / run / "mean_z.npy") if which == "mean" else np.array(json.loads(which))
    base = yaml.safe_load(open(E / "minifly" / "v3_2.yaml"))
    merged = deep_merge(base, params.to_overrides(z))
    head = (
        f"# MiniFly v3_2 + CMA-ES decoder parameters (RL pilot, run {run}, {which})\n"
        "# generated by rl/validate.py export; values vs v3_2:\n"
        + "".join(f"#   {n}: {v0} -> {v}\n" for (n, _, v0, *_), v in zip(params.SPEC, params.describe(z).values()))
    )
    ES_YAML.write_text(head + yaml.safe_dump(merged, sort_keys=False))
    print(ES_YAML.read_text())


def seeds(s: str) -> list[int]:
    a, _, b = s.partition("-")
    return list(range(int(a), int(b or a) + 1))


def rtf_ok(d: Path) -> bool:
    try:
        for line in open(d / "rtf.log"):
            if line.startswith("RTF run"):
                return float(line.split()[2]) >= 0.95
    except FileNotFoundError:
        pass
    return False


def gazebo(seed_list: list[int], only: str = "v3_2,es") -> None:
    arms = {k: v for k, v in {"v3_2": E / "minifly" / "v3_2.yaml", "es": ES_YAML}.items() if k in only.split(",")}
    for s in seed_list:
        for arm, cfg in arms.items():
            tag = f"val_{arm}_s{s}"
            d = RUNS / tag
            if (d / "run.json").exists() and rtf_ok(d):
                continue
            for _ in range(2):
                subprocess.run(
                    ["bash", str(Path.home() / "sim" / "rl_exp" / "gz_g4_rl.sh"), "ecps295_cage20.sdf", tag, f"{ARGS} --seed {s} --config {cfg}"],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    env={**__import__("os").environ, "NAV": "gps"},
                )
                if (d / "run.json").exists() and rtf_ok(d):
                    break
            print(tag, "ok" if (d / "run.json").exists() else "FAILED", flush=True)


def load(arm: str, seed_list: list[int], src: str) -> list[dict]:
    out = []
    if src == "gazebo":
        for s in seed_list:
            p = RUNS / f"val_{arm}_s{s}" / "run.json"
            if p.exists():
                out.append(json.load(open(p)))
    else:
        for line in open(E / "rl" / "out" / f"val_twin_{arm}.jsonl"):
            out.append(json.loads(line))
    return out


def summary(rs: list[dict]) -> dict:
    if not rs:
        return {"n": 0}
    g = lambda k: np.array([r[k] for r in rs], float)  # noqa: E731
    return {
        "n": len(rs),
        "contact_runs": int((g("contact_episodes") > 0).sum()),
        "contact_rate": round(float((g("contact_episodes") > 0).mean()), 3),
        "contacts_mean": round(float(g("contact_episodes").mean()), 2),
        "near_mean": round(float(g("near_miss_episodes").mean()), 2),
        "minclr_p10": round(float(np.percentile(g("min_clearance_m"), 10)), 3),
        "coverage_mean": round(float(g("coverage").mean()), 3),
        "path_mean": round(float(g("path_m").mean()), 1),
        "escapes_mean": round(float(g("escapes").mean()), 2),
        "fence_turn_s_mean": round(float(g("fence_turn_s").mean()), 1),
    }


def report(seed_list: list[int], src: str) -> None:
    from scipy.stats import fisher_exact, mannwhitneyu

    a, b = load("v3_2", seed_list, src), load("es", seed_list, src)
    sa, sb = summary(a), summary(b)
    print(f"[{src}]")
    for k in sa:
        print(f"  {k:18s} v3_2 {sa[k]!s:>8}   es {sb.get(k)!s:>8}")
    if a and b:
        ca, cb = sa["contact_runs"], sb["contact_runs"]
        print(f"  Fisher contact runs p = {fisher_exact([[ca, len(a) - ca], [cb, len(b) - cb]])[1]:.4f}")
        for k in ("near_miss_episodes", "coverage", "contact_episodes"):
            print(f"  Mann-Whitney {k:18s} p = {mannwhitneyu([r[k] for r in a], [r[k] for r in b]).pvalue:.4f}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["export", "twin", "gazebo", "report"])
    ap.add_argument("--run", default="es1")
    ap.add_argument("--which", default="mean")
    ap.add_argument("--seeds", default="0-31")
    ap.add_argument("--src", default="gazebo", choices=["gazebo", "twin"])
    ap.add_argument("--procs", type=int, default=10)
    ap.add_argument("--arms", default="v3_2,es")
    ap.add_argument("--space", default="default", choices=["default", "wide"])
    ap.add_argument("--out-yaml", default="", help="export target (default minifly/v3_2_es.yaml)")
    a = ap.parse_args()
    params.set_space(a.space)
    if a.out_yaml:
        ES_YAML = Path(a.out_yaml)
    if a.cmd == "export":
        export(a.run, a.which)
    elif a.cmd == "twin":
        from rl.batch import run_jobs

        for arm, cfg in (("v3_2", "v3_2"), ("es", str(ES_YAML))):
            out = E / "rl" / "out" / f"val_twin_{arm}.jsonl"
            out.unlink(missing_ok=True)
            run_jobs([{"variant": cfg, "world": "cage20", "seed": s, "seconds": 120} for s in seeds(a.seeds)], a.procs, str(out))
        report(seeds(a.seeds), "twin")
    elif a.cmd == "gazebo":
        gazebo(seeds(a.seeds), a.arms)
    else:
        report(seeds(a.seeds), a.src)
